# Generated by Django 3.1.5 on 2021-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Name', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='patronymic',
            field=models.CharField(default='Patronymic', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='Surname', max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Subject', max_length=60),
        ),
    ]
